### ISSUE TITLE
Error getting Junction Temp info for amd

### ISSUE THREAD

**Issue by dubigrasu** [UnknownSuperficialNight/nvidia-fan-control#3]
I'm getting a `Error getting Junction Temp info for amd`, then exit with a RX590 AMD card.
I only have a sensor for **edge** (temp1_input), so no **junction** or **memory** sensors listed in /sys/class/hwmon/hwmon*.

**Comment by UnknownSuperficialNight** [comment]
I made a quick [Commit](https://github.com/UnknownSuperficialNight/nvidia-fan-control/commit/de761a3b18f82eaee2c74d167832203167e4a0f9) that should hopefully solve the issue. You can use the [pre-compiled binary's](https://github.com/UnknownSuperficialNight/nvidia-fan-control/releases/tag/Rust-version-v0.1.4) or compile from main branch.

Let me know how it goes.

**Comment by dubigrasu** [comment]
Yes, it works now, thanks.
Couple of thoughts though:
The long messages that warns that a sensors might be missing are a bit obtrusive being displayed all the time on screen. Maybe make them disappear after few seconds or make them shorter, like _X Temp info not available_ or similar?

**Comment by UnknownSuperficialNight** [comment]
> Yes, it works now, thanks. Couple of thoughts though: The long messages that warns that a sensors might be missing are a bit obtrusive being displayed all the time on screen. Maybe make them disappear after few seconds or make them shorter, like _X Temp info not available_ or similar?

Sure, I can look into it on my model GPU. I have all three sensors, so I cannot really test it. If you would not mind, could you please post what the output is? 

~Additionally, the delay should only last for a moment~ Never mind, I made a mistake. I was tired, and while programming, I mistakenly thought that it was outside the loop. My intention was to display the message once for five seconds on startup. 

For the time being, please use --amd; it should bypass and resolve the issue. Let me know if it does, and I will work on a commit.

**Comment by UnknownSuperficialNight** [comment]
New [commit](https://github.com/UnknownSuperficialNight/nvidia-fan-control/commit/39a1744cb1724c937581cf0a9a04089b334fe592) and [release](https://github.com/UnknownSuperficialNight/nvidia-fan-control/releases/tag/Rust-version-v0.1.5) has been made let me know how it goes.

**Comment by dubigrasu** [comment]
All seems good now. 
With `--amd` it bypasses the error message and the output is:
**Gpu temp
Current fan RPM
Current fan speed**
Without `--amd` the error message is displayed only for few seconds then goes into the above mentioned output.
As far as I'm concerned, the bug is solved now, many thanks.
